// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://phpxtliftlhookxcwnqk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBocHh0bGlmdGxob29reGN3bnFrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzODI5MDYsImV4cCI6MjA3Mzk1ODkwNn0.2ijdTQagayPh-RM-CaKA-1JYlXyegBz44ZqeOcAhV2U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});